name: Push to Buf Schema Registry
# This workflow runs when changes to proto files are pushed to main
# and then pushes these changes on to the Buf Schema Registry at
# https://buf.build/evmos/evmos
on:
  push:
    tags:
      - "v*.*.*"
    paths:
      - "proto/**"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      # Push Evmos protos to the Buf Schema Registry
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          draft: ${{ github.ref_name != 'main'}}
