name: "Pull Request Labeler"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  triage:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
