name: Protobuf
# Protobuf runs buf (https://buf.build/) lint and check-breakage
# This workflow is only run when a .proto file has been changed
on:
  pull_request:
    paths:
      - "proto/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.proto
            **/buf.yaml
            buf.work.yaml
            buf.gen.yaml
      - run: |
          make proto-gen
#        if: env.GIT_DIFF

  lint:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.15.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
